### PR TITLE
[13.0][ADD] Add helper functions that make the migration of tax tags for localizations modules l10n_* a lot easier.

### PR DESCRIPTION
**Pull request by ddejong-therp**
I'm using these functions in the migration script I'm going to create a pull request for l10n_nl for, but they should be useful for any localization module. Especially the `unlink_invalid_tax_tags_from_*` functions. When migrating the `account` module from 12 to 13, the tax tags are structured differently; they are assigned to account.tax.repartition.line instead of accoun.tax itself. However, the `account` module copies each tag to each new repartition line that it /could possibly/ belong to. This causes issues in the migrated instance in 13.0 and beyond.

I'm using these functions here: https://github.com/OCA/OpenUpgrade/pull/3184

### CODE REVIEW

File: openupgradelib/openupgrade_130.py [hunk 1]
```diff
@@ -0,0 +1,179 @@
+# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
+
+"""Tools specific for migrating from Odoo 12.0 to 13.0.
+"""
+
+import logging
+from . import openupgrade
+
+_logger = logging.getLogger('OpenUpgrade')
+_logger.setLevel(logging.DEBUG)
```
Comment (NL66278) [inline openupgradelib/openupgrade_130.py:10]: Don't do this. Should be set from configuration. If messages are important enough that by default you want to show them, make them info messages.

Comment (ddejong-therp) [reply openupgradelib/openupgrade_130.py]: Alright, I removed the line.

**Comment by wytzejan** [comment]
@ddejong-therp can this be merged already? I'm in the middle of a Odoo 12 to 13 migration and I get the following error now: `ImportError: cannot import name 'openupgrade_130' from 'openupgradelib'`. https://github.com/OCA/OpenUpgrade/pull/3184 was already merged but it needs the changes in this PR I think?

**Comment by StefanRijnhart** [comment]
Merging because it is used in https://github.com/OCA/OpenUpgrade/pull/3184.

File: openupgradelib/openupgrade_130.py [hunk 2]
```diff
@@ -0,0 +1,177 @@
...
+def unlink_invalid_tax_tags_from_move_lines(
+        env, base_tag_xmlids, tax_tag_xmlids):
+    openupgrade.logged_query(env.cr, """
+        DELETE FROM account_account_tag_account_move_line_rel r
+        WHERE
+            account_account_tag_id IN (
+                SELECT res_id FROM ir_model_data
+                WHERE
+                    model = 'account.account.tag' AND
+                    module = 'l10n_nl' AND
```
Comment (MiquelRForgeFlow) [inline openupgradelib/openupgrade_130.py:113]: l10n_nl?

File: openupgradelib/openupgrade_130.py [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+            )
+    """)
+    openupgrade.logged_query(env.cr, """
+        DELETE FROM account_account_tag_account_move_line_rel r
+        WHERE
+            account_account_tag_id IN (
+                SELECT res_id FROM ir_model_data
+                WHERE
+                    model = 'account.account.tag' AND
+                    module = 'l10n_nl' AND
```
Comment (MiquelRForgeFlow) [inline openupgradelib/openupgrade_130.py:128]: l10n_nl?

File: openupgradelib/openupgrade_130.py [hunk 4]
```diff
@@ -0,0 +1,177 @@
...
+            account_tax_repartition_line_id IN (
+                SELECT id FROM account_tax_repartition_line
+                WHERE id = r.account_tax_repartition_line_id
+                    AND repartition_type = 'base'
+            ) AND
+            account_account_tag_id IN (
+                SELECT res_id FROM ir_model_data
+                WHERE
+                    model = 'account.account.tag' AND
+                    module = 'l10n_nl' AND
```
Comment (MiquelRForgeFlow) [inline openupgradelib/openupgrade_130.py:158]: l10n_nl?

File: openupgradelib/openupgrade_130.py [hunk 5]
```diff
@@ -0,0 +1,177 @@
...
+            account_tax_repartition_line_id IN (
+                SELECT id FROM account_tax_repartition_line
+                WHERE id = r.account_tax_repartition_line_id
+                    AND repartition_type = 'tax'
+            ) AND
+            account_account_tag_id IN (
+                SELECT res_id FROM ir_model_data
+                WHERE
+                    model = 'account.account.tag' AND
+                    module = 'l10n_nl' AND
```
Comment (MiquelRForgeFlow) [inline openupgradelib/openupgrade_130.py:174]: l10n_nl?

**Comment by ddejong-therp** [comment]
Oh dear, will fix it asap!
